package com.phone.dao;

import com.phone.pojo.City;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int deleteByPrimaryKey(Double cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    City selectByPrimaryKey(Double cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int updateByPrimaryKey(City record);
}