package com.phone.dao;

import com.phone.pojo.City;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    int deleteByPrimaryKey(Integer city);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    City selectByPrimaryKey(Integer city);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    int updateByPrimaryKey(City record);
}