package com.phone.dao;

import java.util.List;

import com.phone.pojo.City;

public interface CityMapper {
	
	
	/**
	 * 查询市州
	 */
	
	List<City> selectAllCity(int pv_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    int insertSelective(City record);
}