package com.phone.dao;

import com.phone.pojo.Product_Model_Rel;

public interface Product_Model_RelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int insert(Product_Model_Rel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int insertSelective(Product_Model_Rel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    Product_Model_Rel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int updateByPrimaryKeySelective(Product_Model_Rel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_rel
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int updateByPrimaryKey(Product_Model_Rel record);
}