package com.phone.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.phone.pojo.Product;

public interface ProductMapper {
	
	
	List<Product> queryProductByType(@Param("type") String type, @Param("headnum") String headnum,
			@Param("endnum") String endnum);	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    Product selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    int updateByPrimaryKey(Product record);
}