package com.phone.dao;

import com.phone.pojo.Product_Type;

public interface Product_TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    int insert(Product_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    int insertSelective(Product_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    Product_Type selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    int updateByPrimaryKeySelective(Product_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    int updateByPrimaryKey(Product_Type record);
}