package com.phone.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.phone.pojo.Product;

public interface ProductMapper {
	
	
	  List<Product> queryProductByType(@Param("type") int type, @Param("headnum") int headnum,@Param("endnum") int endnum) ;
		  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    Product selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Dec 14 09:35:22 CST 2017
     */
    int updateByPrimaryKey(Product record);
}