package com.phone.dao;

import com.phone.pojo.Product_bh_order;

public interface Product_bh_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    int deleteByPrimaryKey(Integer bhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    int insert(Product_bh_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    int insertSelective(Product_bh_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    Product_bh_order selectByPrimaryKey(Integer bhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    int updateByPrimaryKeySelective(Product_bh_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_bh_order
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    int updateByPrimaryKey(Product_bh_order record);
}