package com.phone.dao;

import java.util.List;

import com.phone.pojo.Product_picture;

public interface Product_pictureMapper {
	
	
	List<Product_picture> selectProductPicture(Integer pid);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    int deleteByPrimaryKey(Integer prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    int insert(Product_picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    int insertSelective(Product_picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    Product_picture selectByPrimaryKey(Integer prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    int updateByPrimaryKeySelective(Product_picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Apr 25 09:35:13 CST 2018
     */
    int updateByPrimaryKey(Product_picture record);

    //查询一个产品的所有图片信息
	List<Product_picture> qryAllProductPictureByPid(int pid);
}