package com.phone.dao;

import java.util.List;

import com.phone.pojo.Province;

public interface ProvinceMapper {

	/**
	 * 查询所有的省份
	 */
	List<Province> selectAllProvince();
	
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    Province selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    int updateByPrimaryKey(Province record);
}