package com.phone.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.phone.pojo.Province;

public interface ProvinceMapper {
	
	
	/**
	 * 查询所有的省份
	 */
	List<Province> selectAllProvince();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    int insertSelective(Province record);

	Province selectProvinceById(int pv_id);
}