package com.phone.dao;

import java.util.List;

import com.phone.pojo.UserAddress;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    int insertSelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    UserAddress selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    int updateByPrimaryKeySelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraddress
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    int updateByPrimaryKey(UserAddress record);

	List<UserAddress> selectByUid(int uid);

	int updateToUnStatus(int uid);
}