package com.phone.pojo;

public class Brand_Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_type.brand_id
     *
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_type.brand_name
     *测试
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    private String brandName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_type.brand_id
     *
     * @return the value of brand_type.brand_id
     *
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_type.brand_id
     *
     * @param brandId the value for brand_type.brand_id
     *
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_type.brand_name
     *
     * @return the value of brand_type.brand_name
     *
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_type.brand_name
     *
     * @param brandName the value for brand_type.brand_name
     *
     * @mbggenerated Thu Dec 07 14:44:02 CST 2017
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
}