package com.phone.pojo;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.order_id
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.uid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.pid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.count
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cid
     *
     * @return the value of cart.cid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cid
     *
     * @param cid the value for cart.cid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.order_id
     *
     * @return the value of cart.order_id
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.order_id
     *
     * @param orderId the value for cart.order_id
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.uid
     *
     * @return the value of cart.uid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.uid
     *
     * @param uid the value for cart.uid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.pid
     *
     * @return the value of cart.pid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.pid
     *
     * @param pid the value for cart.pid
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.count
     *
     * @return the value of cart.count
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.count
     *
     * @param count the value for cart.count
     *
     * @mbggenerated Wed May 02 09:03:00 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    
    
	public Cart(Integer cid, String orderId, Integer uid, Integer pid, Integer count) {
		super();
		this.cid = cid;
		this.orderId = orderId;
		this.uid = uid;
		this.pid = pid;
		this.count = count;
	}

	@Override
	public String toString() {
		return "Cart [cid=" + cid + ", orderId=" + orderId + ", uid=" + uid + ", pid=" + pid + ", count=" + count + "]";
	}
	
}