package com.phone.pojo;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private Double cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.pycode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private String pycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.postcode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.areacode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.pid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cid
     *
     * @return the value of city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public Double getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cid
     *
     * @param cid the value for city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setCid(Double cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cname
     *
     * @return the value of city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cname
     *
     * @param cname the value for city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.pycode
     *
     * @return the value of city.pycode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public String getPycode() {
        return pycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.pycode
     *
     * @param pycode the value for city.pycode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setPycode(String pycode) {
        this.pycode = pycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.postcode
     *
     * @return the value of city.postcode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.postcode
     *
     * @param postcode the value for city.postcode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.areacode
     *
     * @return the value of city.areacode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.areacode
     *
     * @param areacode the value for city.areacode
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.pid
     *
     * @return the value of city.pid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.pid
     *
     * @param pid the value for city.pid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}