package com.phone.pojo;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     * list
     */
    private Double cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    private String cname;

    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cid
     *
     * @return the value of city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public Double getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cid
     *
     * @param cid the value for city.cid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setCid(Double cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cname
     *
     * @return the value of city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cname
     *
     * @param cname the value for city.cname
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.pid
     *
     * @return the value of city.pid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.pid
     *
     * @param pid the value for city.pid
     *
     * @mbggenerated Tue Oct 10 16:25:09 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}