package com.phone.pojo;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pr_address
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String prAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer modelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pid
     *
     * @return the value of picture.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pid
     *
     * @param pid the value for picture.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pr_address
     *
     * @return the value of picture.pr_address
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getPrAddress() {
        return prAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pr_address
     *
     * @param prAddress the value for picture.pr_address
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPrAddress(String prAddress) {
        this.prAddress = prAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.model_id
     *
     * @return the value of picture.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.model_id
     *
     * @param modelId the value for picture.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
}