package com.phone.pojo;

import java.util.Date;

public class Product_comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.comid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private Integer comid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.pid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.uid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.commentTime
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private Date commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.commentMsg
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private String commentmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.status
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.comid
     *
     * @return the value of product_comment.comid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.comid
     *
     * @param comid the value for product_comment.comid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.pid
     *
     * @return the value of product_comment.pid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.pid
     *
     * @param pid the value for product_comment.pid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.uid
     *
     * @return the value of product_comment.uid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.uid
     *
     * @param uid the value for product_comment.uid
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.commentTime
     *
     * @return the value of product_comment.commentTime
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.commentTime
     *
     * @param commenttime the value for product_comment.commentTime
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.commentMsg
     *
     * @return the value of product_comment.commentMsg
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public String getCommentmsg() {
        return commentmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.commentMsg
     *
     * @param commentmsg the value for product_comment.commentMsg
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setCommentmsg(String commentmsg) {
        this.commentmsg = commentmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.status
     *
     * @return the value of product_comment.status
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.status
     *
     * @param status the value for product_comment.status
     *
     * @mbggenerated Mon May 21 21:51:40 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public Product_comment() {
		// TODO Auto-generated constructor stub
	}

	public Product_comment(Integer comid, Integer pid, Integer uid, Date commenttime, String commentmsg,
			Integer status) {
		super();
		this.comid = comid;
		this.pid = pid;
		this.uid = uid;
		this.commenttime = commenttime;
		this.commentmsg = commentmsg;
		this.status = status;
	}

	@Override
	public String toString() {
		return "Product_comment [comid=" + comid + ", pid=" + pid + ", uid=" + uid + ", commenttime=" + commenttime
				+ ", commentmsg=" + commentmsg + ", status=" + status + "]";
	}
    
}