package com.phone.pojo;

public class Product_Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.type_id
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.type_name
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.type_id
     *
     * @return the value of product_type.type_id
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.type_id
     *
     * @param typeId the value for product_type.type_id
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.type_name
     *
     * @return the value of product_type.type_name
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.type_name
     *
     * @param typeName the value for product_type.type_name
     *
     * @mbggenerated Fri Oct 27 10:55:21 CST 2017
     */
    
    public Product_Type() {
		// TODO Auto-generated constructor stub
	}
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

	public Product_Type(Integer typeId, String typeName) {
		super();
		this.typeId = typeId;
		this.typeName = typeName;
	}

	@Override
	public String toString() {
		return "Product_Type [typeId=" + typeId + ", typeName=" + typeName + "]";
	}
    
}