package com.phone.pojo;

import java.util.Date;

public class Product_bh_order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.bhid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Integer bhid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.order_id
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.uid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.pid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.cout
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Integer cout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.finish_time
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_bh_order.price
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.bhid
     *
     * @return the value of product_bh_order.bhid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Integer getBhid() {
        return bhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.bhid
     *
     * @param bhid the value for product_bh_order.bhid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setBhid(Integer bhid) {
        this.bhid = bhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.order_id
     *
     * @return the value of product_bh_order.order_id
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.order_id
     *
     * @param orderId the value for product_bh_order.order_id
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.uid
     *
     * @return the value of product_bh_order.uid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.uid
     *
     * @param uid the value for product_bh_order.uid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.pid
     *
     * @return the value of product_bh_order.pid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.pid
     *
     * @param pid the value for product_bh_order.pid
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.cout
     *
     * @return the value of product_bh_order.cout
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Integer getCout() {
        return cout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.cout
     *
     * @param cout the value for product_bh_order.cout
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setCout(Integer cout) {
        this.cout = cout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.finish_time
     *
     * @return the value of product_bh_order.finish_time
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.finish_time
     *
     * @param finishTime the value for product_bh_order.finish_time
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_bh_order.price
     *
     * @return the value of product_bh_order.price
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_bh_order.price
     *
     * @param price the value for product_bh_order.price
     *
     * @mbggenerated Tue May 01 22:59:25 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}