package com.phone.pojo;

public class Product_Model_Rel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.model_name
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.color
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.pr_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer prId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_model_rel.stock
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.model_id
     *
     * @return the value of product_model_rel.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.model_id
     *
     * @param modelId the value for product_model_rel.model_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.model_name
     *
     * @return the value of product_model_rel.model_name
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.model_name
     *
     * @param modelName the value for product_model_rel.model_name
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.pid
     *
     * @return the value of product_model_rel.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.pid
     *
     * @param pid the value for product_model_rel.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.price
     *
     * @return the value of product_model_rel.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.price
     *
     * @param price the value for product_model_rel.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.color
     *
     * @return the value of product_model_rel.color
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.color
     *
     * @param color the value for product_model_rel.color
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.pr_id
     *
     * @return the value of product_model_rel.pr_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.pr_id
     *
     * @param prId the value for product_model_rel.pr_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model_rel.stock
     *
     * @return the value of product_model_rel.stock
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model_rel.stock
     *
     * @param stock the value for product_model_rel.stock
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}