package com.phone.pojo;

public class Product_attr_biz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_biz.pid
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_biz.attr_code
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_biz.attr_name
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_attr_biz.attr_desc
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    private String attrDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_biz.pid
     *
     * @return the value of product_attr_biz.pid
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_biz.pid
     *
     * @param pid the value for product_attr_biz.pid
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_biz.attr_code
     *
     * @return the value of product_attr_biz.attr_code
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_biz.attr_code
     *
     * @param attrCode the value for product_attr_biz.attr_code
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_biz.attr_name
     *
     * @return the value of product_attr_biz.attr_name
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_biz.attr_name
     *
     * @param attrName the value for product_attr_biz.attr_name
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attr_biz.attr_desc
     *
     * @return the value of product_attr_biz.attr_desc
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public String getAttrDesc() {
        return attrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attr_biz.attr_desc
     *
     * @param attrDesc the value for product_attr_biz.attr_desc
     *
     * @mbggenerated Wed Apr 25 08:18:24 CST 2018
     */
    public void setAttrDesc(String attrDesc) {
        this.attrDesc = attrDesc;
    }
    
    public Product_attr_biz() {
		// TODO Auto-generated constructor stub
	}

    
    
	public Product_attr_biz(Integer pid, String attrCode, String attrName, String attrDesc) {
		super();
		this.pid = pid;
		this.attrCode = attrCode;
		this.attrName = attrName;
		this.attrDesc = attrDesc;
	}

	@Override
	public String toString() {
		return "Product_attr_biz [pid=" + pid + ", attrCode=" + attrCode + ", attrName=" + attrName + ", attrDesc="
				+ attrDesc + "]";
	}
    
    
    
}