package com.phone.pojo;

import java.util.Date;

public class Product_b_order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.oid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.order_id
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.uid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.pid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.addressId
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.cout
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer cout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.price
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.order_time
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_b_order.order_status
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    private Integer orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.oid
     *
     * @return the value of product_b_order.oid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.oid
     *
     * @param oid the value for product_b_order.oid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.order_id
     *
     * @return the value of product_b_order.order_id
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.order_id
     *
     * @param orderId the value for product_b_order.order_id
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.uid
     *
     * @return the value of product_b_order.uid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.uid
     *
     * @param uid the value for product_b_order.uid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.pid
     *
     * @return the value of product_b_order.pid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.pid
     *
     * @param pid the value for product_b_order.pid
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.addressId
     *
     * @return the value of product_b_order.addressId
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.addressId
     *
     * @param addressid the value for product_b_order.addressId
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.cout
     *
     * @return the value of product_b_order.cout
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getCout() {
        return cout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.cout
     *
     * @param cout the value for product_b_order.cout
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setCout(Integer cout) {
        this.cout = cout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.price
     *
     * @return the value of product_b_order.price
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.price
     *
     * @param price the value for product_b_order.price
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.order_time
     *
     * @return the value of product_b_order.order_time
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.order_time
     *
     * @param orderTime the value for product_b_order.order_time
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_b_order.order_status
     *
     * @return the value of product_b_order.order_status
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_b_order.order_status
     *
     * @param orderStatus the value for product_b_order.order_status
     *
     * @mbggenerated Sun May 13 16:11:17 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

	public Product_b_order(Integer oid, String orderId, Integer uid, Integer pid, Integer addressid, Integer cout,
			Double price, Date orderTime, Integer orderStatus) {
		super();
		this.oid = oid;
		this.orderId = orderId;
		this.uid = uid;
		this.pid = pid;
		this.addressid = addressid;
		this.cout = cout;
		this.price = price;
		this.orderTime = orderTime;
		this.orderStatus = orderStatus;
	}

	@Override
	public String toString() {
		return "Product_b_order [oid=" + oid + ", orderId=" + orderId + ", uid=" + uid + ", pid=" + pid + ", addressid="
				+ addressid + ", cout=" + cout + ", price=" + price + ", orderTime=" + orderTime + ", orderStatus="
				+ orderStatus + "]";
	}
    
    public Product_b_order() {
		// TODO Auto-generated constructor stub
	}
    
}