package com.phone.pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_id
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_id
     *
     * @return the value of product.type_id
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_id
     *
     * @param typeId the value for product.type_id
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated Wed Apr 25 08:33:14 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}