package com.phone.pojo;

public class Product_picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.pr_id
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    private Integer prId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.pid
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.pr_address
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    private String prAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.pr_status
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    private Integer prStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.pr_id
     *
     * @return the value of product_picture.pr_id
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.pr_id
     *
     * @param prId the value for product_picture.pr_id
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.pid
     *
     * @return the value of product_picture.pid
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.pid
     *
     * @param pid the value for product_picture.pid
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.pr_address
     *
     * @return the value of product_picture.pr_address
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public String getPrAddress() {
        return prAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.pr_address
     *
     * @param prAddress the value for product_picture.pr_address
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public void setPrAddress(String prAddress) {
        this.prAddress = prAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.pr_status
     *
     * @return the value of product_picture.pr_status
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public Integer getPrStatus() {
        return prStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.pr_status
     *
     * @param prStatus the value for product_picture.pr_status
     *
     * @mbggenerated Wed Apr 25 08:51:05 CST 2018
     */
    public void setPrStatus(Integer prStatus) {
        this.prStatus = prStatus;
    }
}