package com.phone.pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.picture
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.avg_price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Double avgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    private Integer discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_id
     *
     * @return the value of product.type_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_id
     *
     * @param typeId the value for product.type_id
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.picture
     *
     * @return the value of product.picture
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.picture
     *
     * @param picture the value for product.picture
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.avg_price
     *
     * @return the value of product.avg_price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Double getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.avg_price
     *
     * @param avgPrice the value for product.avg_price
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setAvgPrice(Double avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbggenerated Wed Dec 13 10:54:52 CST 2017
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
}