package com.phone.pojo;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pv_id
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    private Integer pvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pv_id
     *
     * @return the value of province.pv_id
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    public Integer getPvId() {
        return pvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pv_id
     *
     * @param pvId the value for province.pv_id
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    public void setPvId(Integer pvId) {
        this.pvId = pvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbggenerated Thu Apr 26 09:56:12 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}