package com.phone.pojo;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pid
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pid
     *
     * @return the value of province.pid
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pid
     *
     * @param pid the value for province.pid
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbggenerated Sat Oct 07 13:00:32 CST 2017
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}