package com.phone.pojo;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.cid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.uid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.aname
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.phone
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.areaProvince
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String areaprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.areaCity
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String areacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.areaDetail
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String areadetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraddress.areaStatus
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    private String areastatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.cid
     *
     * @return the value of useraddress.cid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.cid
     *
     * @param cid the value for useraddress.cid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.uid
     *
     * @return the value of useraddress.uid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.uid
     *
     * @param uid the value for useraddress.uid
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.aname
     *
     * @return the value of useraddress.aname
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.aname
     *
     * @param aname the value for useraddress.aname
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.phone
     *
     * @return the value of useraddress.phone
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.phone
     *
     * @param phone the value for useraddress.phone
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.areaProvince
     *
     * @return the value of useraddress.areaProvince
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getAreaprovince() {
        return areaprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.areaProvince
     *
     * @param areaprovince the value for useraddress.areaProvince
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setAreaprovince(String areaprovince) {
        this.areaprovince = areaprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.areaCity
     *
     * @return the value of useraddress.areaCity
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getAreacity() {
        return areacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.areaCity
     *
     * @param areacity the value for useraddress.areaCity
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setAreacity(String areacity) {
        this.areacity = areacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.areaDetail
     *
     * @return the value of useraddress.areaDetail
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getAreadetail() {
        return areadetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.areaDetail
     *
     * @param areadetail the value for useraddress.areaDetail
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setAreadetail(String areadetail) {
        this.areadetail = areadetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraddress.areaStatus
     *
     * @return the value of useraddress.areaStatus
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public String getAreastatus() {
        return areastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraddress.areaStatus
     *
     * @param areastatus the value for useraddress.areaStatus
     *
     * @mbggenerated Fri May 04 08:15:19 CST 2018
     */
    public void setAreastatus(String areastatus) {
        this.areastatus = areastatus;
    }

	public UserAddress(Integer cid, Integer uid, String aname, String phone, String areaprovince, String areacity,
			String areadetail, String areastatus) {
		super();
		this.cid = cid;
		this.uid = uid;
		this.aname = aname;
		this.phone = phone;
		this.areaprovince = areaprovince;
		this.areacity = areacity;
		this.areadetail = areadetail;
		this.areastatus = areastatus;
	}

	@Override
	public String toString() {
		return "UserAddress [cid=" + cid + ", uid=" + uid + ", aname=" + aname + ", phone=" + phone + ", areaprovince="
				+ areaprovince + ", areacity=" + areacity + ", areadetail=" + areadetail + ", areastatus=" + areastatus
				+ "]";
	}
    
    
    
    
}